### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by k0nsl** [MarceauKa/Shaarli---SuperHero-Theme#2]
Hello MarceauKa,

Your demo site isn't working. I just wanted to give you a heads up about it in case you hadn't already noticed it.

Relevant information:
![alt text](https://screen.img-cdn.ru/chrome_2016-07-15_00-05-36.png)

I have deployed your theme on my Shaarli site and I have almost completely translated it from French into English; there are only minor traces of French still there.

My site is: https://shaarli.k0nsl.org/

**Comment by MarceauKa** [comment]
Hi! Thank you for your issue.
Yes, I need time to update the theme. Maybe this weekend :)

**Comment by MarceauKa** [comment]
Demo repaired :)
